name: Nuget Build 

on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  push:
    branches:
      - master

jobs:
  nuget: 
    runs-on: macos-latest

    steps:

      - uses: actions/checkout@v1

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.0.2
      
      - name: Add private GitHub registry to NuGet
        run: nuget sources add -name "GitHub" -source "https://nuget.pkg.github.com/masonyc/index.json" -userName masonyc -password ${{ secrets.nuget_password }}

      - name : restore
        run: nuget restore scr/Xamarin.KeyboardHelper.sln

      - name: build 
        run: msbuild scr/Xamarin.KeyboardHelper/Xamarin.KeyboardHelper.csproj /verbosity:normal /t:Rebuild /p:Configuration=Debug
      
      - uses: actions/upload-artifact@v1
        with:
          name: Xamarin.KeyboardHelper
          path: scr/Xamarin.KeyboardHelper/bin/Debug/ 

      - name: Push generated package to GitHub registry
        run: nuget push scr/Xamarin.KeyboardHelper/bin/Debug/*.nupkg -Source "GitHub" -SkipDuplicate
